-- Seed para la tabla de municipios
DO $$
DECLARE
    estado_id int4;
BEGIN
    -- Insertar municipios para cada estado
    -- AGUASCALIENTES
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'AGU';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'AGUASCALIENTES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ASIENTOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'CALVILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'COSÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'JESÚS MARÍA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'PABELLÓN DE ARTEAGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'RINCÓN DE ROMOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'SAN JOSÉ DE GRACIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'TEPEZALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'EL LLANO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'SAN FRANCISCO DE LOS ROMO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- BAJA CALIFORNIA
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'BCN';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ENSENADA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'MEXICALI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'TECATE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'TIJUANA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'PLAYAS DE ROSARITO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- BAJA CALIFORNIA SUR
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'BCS';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'COMONDÚ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'MULEGÉ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'LA PAZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'LOS CABOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'LORETO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    --agrega los municipios para el estado de campeche
    -- CAMPECHE
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'CAM';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'CALKINÍ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'CAMPECHE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'CARMEN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'CHAMPOTÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'HECELCHAKÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'HOPELCHÉN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'PALIZADA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'TENABO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'ESCÁRCEGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'CALAKMUL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'CANDELARIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- CHIHUAHUA
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'CHH';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'AHUMADA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ALDAMA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'AQUILES SERDÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'ASCENSIÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'BACHÍNIVA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'BALLEZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'BATOPILAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'BOCOYNA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'BUENAVENTURA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'CAMARGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'CARICHÍ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'CASAS GRANDES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'CORONADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'COYAME DEL SOTOL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'LA CRUZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'CUAUHTÉMOC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'CUSIHUIRIACHI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'CHIHUAHUA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'CHÍNIPAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'DELICIAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'DR. BELISARIO DOMÍNGUEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'GALEANA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'SANTA ISABEL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'GÓMEZ FARÍAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'GRAN MORELOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'GUACHOCHI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'GUADALUPE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'GUADALUPE Y CALVO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'GUAZAPARES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'HIDALGO DEL PARRAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'HUEJOTITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'IGNACIO ZARAGOZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'JANOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'JIMÉNEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'JULIMES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'LÓPEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('040', 'MADERA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('041', 'MAGUARICHI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('042', 'MANUEL BENAVIDES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('043', 'MATACHÍ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('044', 'MATAMOROS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('045', 'MEOQUI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('046', 'MORELOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('047', 'MORIS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('048', 'NAMIQUIPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('049', 'NONOAVA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('050', 'NUEVO CASAS GRANDES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('051', 'OCAMPO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('052', 'OJINAGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('053', 'PRAXEDIS G. GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('054', 'RIVA PALACIO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('055', 'ROSALES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('056', 'ROSARIO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('057', 'SAN FRANCISCO DE BORJA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('058', 'SAN FRANCISCO DE CONCHOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('059', 'SAN FRANCISCO DEL ORO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('060', 'SANTA BÁRBARA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('061', 'SATEVÓ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('062', 'SAUCILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('063', 'TEMÓSACHIC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('064', 'EL TULE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('065', 'URIQUE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('066', 'URUACHI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('067', 'VALLE DE ZARAGOZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- CHIAPAS
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'CHP';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ACACOYAGUA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ACALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'ACAPETAHUA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'ALTAMIRANO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'AMATÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'AMATENANGO DE LA FRONTERA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'AMATENANGO DEL VALLE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'ANGEL ALBINO CORZO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'ARRIAGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'BEJUCAL DE OCAMPO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'BELLA VISTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'BERRIOZÁBAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'BOCHIL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'EL BOSQUE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'CACAHOATÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'CATAZAJÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'CINTALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'COAPILLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'COMITÁN DE DOMÍNGUEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'LA CONCORDIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'COPAINALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'CHALCHIHUITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'CHAMULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'CHANAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'CHAPULTENANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'CHENALHÓ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'CHIAPA DE CORZO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'CHIAPILLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'CHICOASÉN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'CHICOMUSELO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'CHILÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'ESCUINTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'FRANCISCO LEÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'FRONTERA COMALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'FRONTERA HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'LA GRANDEZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'HUEHUETÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'HUIXTÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'HUITIUPÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('040', 'HUIXTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('041', 'LA INDEPENDENCIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('042', 'IXHUATÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('043', 'IXTACOMITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('044', 'IXTAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('045', 'IXTAPANGAJOYA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('046', 'JIQUIPILAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('047', 'JITOTOL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('048', 'JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('049', 'LARRÁINZAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('050', 'LA LIBERTAD', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('051', 'MAPASTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('052', 'LAS MARGARITAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('053', 'MAZAPA DE MADERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('054', 'MAZATÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('055', 'METAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('056', 'MITONTIC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('057', 'MOTOZINTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('058', 'NICOLÁS RUÍZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('059', 'OCOSINGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('060', 'OCOTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('061', 'OCOZOCOAUTLA DE ESPINOSA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('062', 'OSTUACÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('063', 'OSUMACINTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('064', 'OXCHUC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('065', 'PALENQUE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('066', 'PANTELHÓ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('067', 'PANTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('068', 'PICHUCALCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('069', 'PIJIJIAPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('070', 'EL PORVENIR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('071', 'VILLA COMALTITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('072', 'PUEBLO NUEVO SOLISTAHUACÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('073', 'RAYÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('074', 'REFORMA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('075', 'LAS ROSAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('076', 'SABANILLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('077', 'SALTO DE AGUA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('078', 'SAN CRISTÓBAL DE LAS CASAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('079', 'SAN FERNANDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('080', 'SILTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('081', 'SIMOJOVEL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('082', 'SITALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('083', 'SOCOLTENANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('084', 'SOLOSUCHIAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('085', 'SOYALÓ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('086', 'SUCHIAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('087', 'SUCHIATE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('088', 'SUNUAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('089', 'TAPACHULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('090', 'TAPALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('091', 'TAPILULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('092', 'TECPATÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('093', 'TENEJAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('094', 'TEOPISCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('096', 'TILA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('097', 'TONALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('098', 'TOTOLAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('099', 'LA TRINITARIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('100', 'TUMBALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('101', 'TUXTLA GUTIÉRREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('102', 'TUXTLA CHICO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('103', 'TUZANTÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('104', 'TZIMOL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('105', 'UNIÓN JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('106', 'VENUSTIANO CARRANZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('107', 'VILLA CORZO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('108', 'VILLAFLORES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('109', 'YAJALÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('110', 'SAN LUCAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('111', 'ZINACANTÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('112', 'SAN JUAN CANCUC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('113', 'ALDAMA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('114', 'BENEMÉRITO DE LAS AMÉRICAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('115', 'MARAVILLA TENEJAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('116', 'MARQUÉS DE COMILLAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('117', 'MONTECRISTO DE GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('118', 'SAN ANDRÉS DURAZNAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('119', 'SANTIAGO EL PINAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('120', 'CAPITÁN LUIS ÁNGEL VIDAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('121', 'RINCÓN CHAMULA SAN PEDRO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('122', 'EL PARRAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('123', 'EMILIANO ZAPATA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('124', 'MEZCALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- CIUDAD DE MÉXICO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'CMX';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('002', 'AZCAPOTZALCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'COYOACÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'CUAJIMALPA DE MORELOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'GUSTAVO A. MADERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'IZTACALCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'IZTAPALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'LA MAGDALENA CONTRERAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'MILPA ALTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'ÁLVARO OBREGÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'TLÁHUAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'TLALPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'XOCHIMILCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'BENITO JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'CUAUHTÉMOC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'MIGUEL HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'VENUSTIANO CARRANZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- COAHUILA
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'COA';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ABASOLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ACUÑA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'ARTEAGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'CANDELA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'CASTAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'CUATRO CIÉNEGAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'ESCOBEDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'FRANCISCO I. MADERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'FRONTERA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'GENERAL CEPEDA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'JIMÉNEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'LAMADRID', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'MATAMOROS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'MONCLOVA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'MORELOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'MÚZQUIZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'NADADORES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'NAVA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'OCAMPO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'PARRAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'PIEDRAS NEGRAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'PROGRESO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'RAMOS ARIZPE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'SABINAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'SACRAMENTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'SALTILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'SAN BUENAVENTURA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'SAN JUAN DE SABINAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'SAN PEDRO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'SIERRA MOJADA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'TORREÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'VIESCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'VILLA UNIÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'ZARAGOZA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- COLIMA
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'COL';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ARMERÍA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'COLIMA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'COMALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'COQUIMATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'CUAUHTÉMOC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'IXTLAHUACÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'MANZANILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'MINATITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'TECOMÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'VILLA DE ÁLVAREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- DURANGO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'DUR';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'CANATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'CANELAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'CONETO DE COMONFORT', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'CUENCAMÉ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'DURANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'GENERAL SIMÓN BOLÍVAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'GÓMEZ PALACIO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'GUADALUPE VICTORIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'GUANACEVÍ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'INDÉ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'LERDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'MAPIMÍ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'MEZQUITAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'NAZAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'NOMBRE DE DIOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'OCAMPO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'EL ORO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'OTÁEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'PÁNUCO DE CORONADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'PEÑÓN BLANCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'POANAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'PUEBLO NUEVO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'RODEO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'SAN BERNARDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'SAN DIMAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'SAN JUAN DE GUADALUPE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'SAN JUAN DEL RÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'SAN LUIS DEL CORDERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'SAN PEDRO DEL GALLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'SANTA CLARA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'SANTIAGO PAPASQUIARO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'SÚCHIL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'TAMAZULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'TEPEHUANES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'TLAHUALILO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'TOPIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'VICENTE GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'NUEVO IDEAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- EXTRANJERO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'EX';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('571', 'EXTRANJERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- GUERRERO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'GRO';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ACAPULCO DE JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'AHUACUOTZINGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'AJUCHITLÁN DEL PROGRESO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'ALCOZAUCA DE GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'ALPOYECA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'APAXTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'ARCELIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'ATENANGO DEL RÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'ATLAMAJALCINGO DEL MONTE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'ATLIXTAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'ATOYAC DE ÁLVAREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'AYUTLA DE LOS LIBRES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'AZOYÚ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'BENITO JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'BUENAVISTA DE CUÉLLAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'COAHUAYUTLA DE JOSÉ MARÍA IZAZAGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'COCULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'COPALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'COPALILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'COPANATOYAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'COYUCA DE BENÍTEZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'COYUCA DE CATALÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'CUAJINICUILAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'CUALÁC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'CUAUTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'CUETZALA DEL PROGRESO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'CUTZAMALA DE PINZÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'CHILAPA DE ÁLVAREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'CHILPANCINGO DE LOS BRAVO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'FLORENCIO VILLARREAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'GENERAL CANUTO A. NERI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'GENERAL HELIODORO CASTILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'HUAMUXTITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'HUITZUCO DE LOS FIGUEROA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'IGUALA DE LA INDEPENDENCIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'IGUALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'IXCATEOPAN DE CUAUHTÉMOC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'ZIHUATANEJO DE AZUETA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'JUAN R. ESCUDERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('040', 'LEONARDO BRAVO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('041', 'MALINALTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('042', 'MÁRTIR DE CUILAPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('043', 'METLATÓNOC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('044', 'MOCHITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('045', 'OLINALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('046', 'OMETEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('047', 'PEDRO ASCENCIO ALQUISIRAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('048', 'PETATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('049', 'PILCAYA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('050', 'PUNGARABATO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('051', 'QUECHULTENANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('052', 'SAN LUIS ACATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('053', 'SAN MARCOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('054', 'SAN MIGUEL TOTOLAPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('055', 'TAXCO DE ALARCÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('056', 'TECOANAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('057', 'TÉCPAN DE GALEANA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('058', 'TELOLOAPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('059', 'TEPECOACUILCO DE TRUJANO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('060', 'TETIPAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('061', 'TIXTLA DE GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('062', 'TLACOACHISTLAHUACA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('063', 'TLACOAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('064', 'TLALCHAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('065', 'TLALIXTAQUILLA DE MALDONADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('066', 'TLAPA DE COMONFORT', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('067', 'TLAPEHUALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('068', 'LA UNIÓN DE ISIDORO MONTES DE OCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('069', 'XALPATLÁHUAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('070', 'XOCHIHUEHUETLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('071', 'XOCHISTLAHUACA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('072', 'ZAPOTITLÁN TABLAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('073', 'ZIRÁNDARO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('074', 'ZITLALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('075', 'EDUARDO NERI', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('076', 'ACATEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('077', 'MARQUELIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('078', 'COCHOAPA EL GRANDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('079', 'JOSÉ JOAQUÍN DE HERRERA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('080', 'JUCHITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('081', 'ILIATENCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- GUANAJUATO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'GUA';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ABASOLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ACÁMBARO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'SAN MIGUEL DE ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'APASEO EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'APASEO EL GRANDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'ATARJEA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'CELAYA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'MANUEL DOBLADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'COMONFORT', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'CORONEO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'CORTAZAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'CUERÁMARO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'DOCTOR MORA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'GUANAJUATO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'HUANÍMARO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'IRAPUATO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'JARAL DEL PROGRESO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'JERÉCUARO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'LEÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'MOROLEÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'OCAMPO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'PÉNJAMO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'PUEBLO NUEVO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'PURÍSIMA DEL RINCÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'ROMITA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'SALAMANCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'SALVATIERRA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'SAN DIEGO DE LA UNIÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'SAN FELIPE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'SAN FRANCISCO DEL RINCÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'SAN JOSÉ ITURBIDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'SAN LUIS DE LA PAZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'SANTA CATARINA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'SANTIAGO DE ANAYA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'SANTIAGO TULANTEPEC DE LUGO GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'SINGUILUCAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'TASQUILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'TECOZAUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('040', 'TENANGO DE DORIA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('041', 'TEPEAPULCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('042', 'TEPEHUACÁN DE GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('043', 'TEPEJI DEL RÍO DE OCAMPO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('044', 'TEPETITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('045', 'TETEPANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('046', 'VILLA DE TEZONTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('047', 'TEZONTEPEC DE ALDAMA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('048', 'TIANGUISTENGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('049', 'TIZAYUCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('050', 'TLAHUELILPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('051', 'TLAHUILTEPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('052', 'TLANALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('053', 'TLANCHINOL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('054', 'TLAXCOAPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('055', 'TOLCAYUCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('056', 'TULA DE ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('057', 'TULANCINGO DE BRAVO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('058', 'XOCHIC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('059', 'XOCHILTIC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('060', 'YAHUALICA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('061', 'ZACUALTIPÁN DE ÁNGELES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('062', 'ZAPOTLÁN DE JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('063', 'ZAPOTITLÁN DE VADILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('064', 'ZAPOTLÁN DEL REY', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('065', 'ZAPOTLANEJO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('066', 'ZAPOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('067', 'ZONTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('068', 'SAN IGNACIO CERRO GORDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- JALISCO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'JAL';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ACATIC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ACATLÁN DE JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'AHUALULCO DE MERCADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'AMACUECA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'AMATITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'AMECA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'SAN JUANITO DE ESCOBEDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'ARANDAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'EL ARENAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'ATEMAJAC DE BRIZUELA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'ATENGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'ATENGUILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'ATOTONILCO EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'ATOYAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'AUTLÁN DE NAVARRO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'AYOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'AYUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'LA BARCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'BOLAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'CABO CORRIENTES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'CASIMIRO CASTILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'CIHUATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'ZAPOTLÁN EL GRANDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'COCULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'COLOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'CONCEPCIÓN DE BUENOS AIRES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'CUAUTITLÁN DE GARCÍA BARRAGÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'CUAUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'CUQUÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'CHAPALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'CHIMALTITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'CHIQUILISTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'DEGOLLADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'EJUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'ENCARNACIÓN DE DÍAZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'ETZATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'EL GRULLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'GUACHINANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'GUADALAJARA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('040', 'HOSTOTIPAQUILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('041', 'HUEJÚCAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('042', 'HUEJUQUILLA EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('043', 'LA HUERTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('044', 'IXTLAHUACÁN DE LOS MEMBRILLOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('045', 'IXTLAHUACÁN DEL RÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('046', 'JALOSTOTITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('047', 'JAMAY', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('048', 'JESÚS MARÍA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('049', 'JILOTLÁN DE LOS DOLORES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('050', 'JOCOTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('051', 'JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('052', 'LAGOS DE MORENO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('053', 'EL LIMÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('054', 'MAGDALENA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('055', 'LA MANZANILLA DE LA PAZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('056', 'MASCOTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('057', 'MAZAMITLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('058', 'MEXTICACÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('059', 'MEZQUITAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('060', 'MIXTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('061', 'OCOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('062', 'OJUELOS DE JALISCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('063', 'PIHUAMO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('064', 'PONCITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('065', 'PUERTO VALLARTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('066', 'VILLA PURIFICACIÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('067', 'QUITUPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('068', 'EL SALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('069', 'SAN CRISTÓBAL DE LA BARRANCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('070', 'SAN DIEGO DE ALEJANDRÍA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('071', 'SAN JUAN DE LOS LAGOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('072', 'SAN JULIÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('073', 'SAN MARCOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('074', 'SAN MARTÍN DE BOLAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('075', 'SAN MARTÍN HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('076', 'SAN MIGUEL EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('077', 'GÓMEZ FARÍAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('078', 'SAN SEBASTIÁN DEL OESTE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('079', 'SANTA MARÍA DE LOS ÁNGELES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('080', 'SAYULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('081', 'TALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('082', 'TALPA DE ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('083', 'TAMAZULA DE GORDIANO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('084', 'TAPALPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('085', 'TECALITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('086', 'TECOLOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('087', 'TECHALUTA DE MONTEGRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('088', 'TENAMAXTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('089', 'TEOPISCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('090', 'TETIPAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('091', 'TETZALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('092', 'TIERRA BLANCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('093', 'TLAJOMULCO DE ZÚÑIGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('094', 'SAN PEDRO TLAQUEPAQUE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('095', 'TOLIMÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('096', 'TOMATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('097', 'TONALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('098', 'TONAYA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('099', 'TONILA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('100', 'TOTOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('101', 'TUXCACUESCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('102', 'TUXCUECA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('103', 'TUXPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('104', 'UNIÓN DE SAN ANTONIO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('105', 'UNIÓN DE TULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('106', 'VALLE DE GUADALUPE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('107', 'VALLE DE JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('108', 'SAN GABRIEL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('109', 'VILLA CORONA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('110', 'VILLA GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('111', 'VILLA HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('112', 'CAÑADAS DE OBREGÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('113', 'YAHUALICA DE GONZÁLEZ GALLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('114', 'ZACOALCO DE TORRES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('115', 'ZAPOPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('116', 'ZAPOTITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('117', 'ZAPOTITLÁN DE VADILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('118', 'ZAPOTLÁN DEL REY', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('119', 'ZAPOTLANEJO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('120', 'SAN IGNACIO CERRO GORDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('121', 'SAN DIEGO DE ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('122', 'SAN JUAN DE LOS LAGOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('123', 'SAN JULIÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('124', 'SAN MARCOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('125', 'SAN MARTÍN DE BOLAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

    -- ESTADO DE MÉXICO
    SELECT id INTO estado_id FROM sat_tbl_estados WHERE clave_estado = 'MEX';
    INSERT INTO sat_tbl_municipios (clave_municipio, descripcion, estado_id, esta_activo, created_at, updated_at)
    VALUES 
        ('001', 'ACAMBAY DE RUÍZ CASTAÑEDA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('002', 'ACOLMAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('003', 'ACULCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('004', 'ALMOLOYA DE ALQUISIRAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('005', 'ALMOLOYA DE JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('006', 'ALMOLOYA DEL RÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('007', 'AMANALCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('008', 'AMATEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('009', 'AMECAMECA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('010', 'APAXCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('011', 'ATENCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('012', 'ATENGUILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('013', 'ATOTONILCO EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('014', 'ATOYAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('015', 'AUTLÁN DE NAVARRO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('016', 'AYOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('017', 'AYUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('018', 'LA BARCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('019', 'BOLAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('020', 'CABO CORRIENTES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('021', 'CASIMIRO CASTILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('022', 'CIHUATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('023', 'ZAPOTLÁN EL GRANDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('024', 'COCULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('025', 'COLOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('026', 'CONCEPCIÓN DE BUENOS AIRES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('027', 'CUAUTITLÁN DE GARCÍA BARRAGÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('028', 'CUAUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('029', 'CUQUÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('030', 'CHAPALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('031', 'CHIMALTITÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('032', 'CHIQUILISTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('033', 'DEGOLLADO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('034', 'EJUTLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('035', 'ENCARNACIÓN DE DÍAZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('036', 'ETZATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('037', 'EL GRULLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('038', 'GUACHINANGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('039', 'GUADALAJARA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('040', 'HOSTOTIPAQUILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('041', 'HUEJÚCAR', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('042', 'HUEJUQUILLA EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('043', 'LA HUERTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('044', 'IXTLAHUACÁN DE LOS MEMBRILLOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('045', 'IXTLAHUACÁN DEL RÍO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('046', 'JALOSTOTITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('047', 'JAMAY', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('048', 'JESÚS MARÍA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('049', 'JILOTLÁN DE LOS DOLORES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('050', 'JOCOTEPEC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('051', 'JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('052', 'LAGOS DE MORENO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('053', 'EL LIMÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('054', 'MAGDALENA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('055', 'LA MANZANILLA DE LA PAZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('056', 'MASCOTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('057', 'MAZAMITLA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('058', 'MEXTICACÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('059', 'MEZQUITAL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('060', 'MIXTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('061', 'OCOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('062', 'OJUELOS DE JALISCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('063', 'PIHUAMO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('064', 'PONCITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('065', 'PUERTO VALLARTA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('066', 'VILLA PURIFICACIÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('067', 'QUITUPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('068', 'EL SALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('069', 'SAN CRISTÓBAL DE LA BARRANCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('070', 'SAN DIEGO DE ALEJANDRÍA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('071', 'SAN JUAN DE LOS LAGOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('072', 'SAN JULIÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('073', 'SAN MARCOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('074', 'SAN MARTÍN DE BOLAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('075', 'SAN MARTÍN HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('076', 'SAN MIGUEL EL ALTO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('077', 'GÓMEZ FARÍAS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('078', 'SAN SEBASTIÁN DEL OESTE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('079', 'SANTA MARÍA DE LOS ÁNGELES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('080', 'SAYULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('081', 'TALA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('082', 'TALPA DE ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('083', 'TAMAZULA DE GORDIANO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('084', 'TAPALPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('085', 'TECALITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('086', 'TECOLOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('087', 'TECHALUTA DE MONTEGRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('088', 'TENAMAXTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('089', 'TEOPISCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('090', 'TETIPAC', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('091', 'TETZALAPA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('092', 'TIERRA BLANCA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('093', 'TLAJOMULCO DE ZÚÑIGA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('094', 'SAN PEDRO TLAQUEPAQUE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('095', 'TOLIMÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('096', 'TOMATLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('097', 'TONALÁ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('098', 'TONAYA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('099', 'TONILA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('100', 'TOTOTLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('101', 'TUXCACUESCO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('102', 'TUXCUECA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('103', 'TUXPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('104', 'UNIÓN DE SAN ANTONIO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('105', 'UNIÓN DE TULA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('106', 'VALLE DE GUADALUPE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('107', 'VALLE DE JUÁREZ', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('108', 'SAN GABRIEL', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('109', 'VILLA CORONA', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('110', 'VILLA GUERRERO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('111', 'VILLA HIDALGO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('112', 'CAÑADAS DE OBREGÓN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('113', 'YAHUALICA DE GONZÁLEZ GALLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('114', 'ZACOALCO DE TORRES', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('115', 'ZAPOPAN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('116', 'ZAPOTITLÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('117', 'ZAPOTITLÁN DE VADILLO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('118', 'ZAPOTLÁN DEL REY', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('119', 'ZAPOTLANEJO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('120', 'SAN IGNACIO CERRO GORDO', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('121', 'SAN DIEGO DE ALLENDE', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('122', 'SAN JUAN DE LOS LAGOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('123', 'SAN JULIÁN', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('124', 'SAN MARCOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('125', 'SAN MARTÍN DE BOLAÑOS', estado_id, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

END $$;
